### ISSUE TITLE
Domain methods seem to be missing

### ISSUE THREAD

**Issue by ChrisM2** [johnsonlee/virt#2]
using `lookupDomainByUUID` on a connection results in:

```
TypeError: Cannot read property 'apply' of undefined
    at Connection.lookupDomainByUUID (/home/labadmin/vm-control/node_modules/virt/index.js:637:44)
    at Connection.(anonymous function) [as lookupDomainByUUID] (/home/labadmin/vm-control/node_modules/virt/index.js:1852:30)
    at Object.<anonymous> (/home/labadmin/vm-control/index.js:19:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

from:

``` javascript
var virt = require('virt'),
    Connection = virt.Connection;
var parseXML = require('xml2js').parseString;

var c = Connection.open('qemu:///system'); // connect to local hypervisor
parseXML(c.getCapabilities(),function (err, result) {
    console.log(result);
});

var hostname = c.getHostname();
console.log(hostname);

var libVersion = c.getLibVersion();
console.log(libVersion);

var nodeInfo = c.getNodeInfo();
console.log(JSON.stringify(nodeInfo));

var domain = c.lookupDomainByUUID('4c81d7e4-a505-4407-847c-74b6b8c01c83')
console.log(domain);
```

Simalar errors seen for other domain functions such as `listDomains`. These functions are listed in `index.js`, but don't seem to be anywhere in the `src` directory.

**Comment by maolcay** [comment]
I confirm.

**Comment by BasToTheMax** [comment]
Any updates?
